### ISSUE TITLE
脚本编辑器无法输入？

### ISSUE THREAD

**Issue by PYUDNG** [NXY666/bower-bird#2]
看了看还蛮有意思的，想试试，于是…

如图：
![截屏2024-06-27 下午5 46 44](https://github.com/NXY666/bower-bird/assets/63054558/9f5ca631-7014-40bc-b48f-ee361d6161c8)
脚本编辑器内拖动左侧块到右侧，出现<请输入>部分文字，但是点击并不能输入
这是我使用姿势不对还是…

**Comment by NXY666** [comment]
你试试用鼠标右键点块，会有一个对话框用于编辑。

**Comment by PYUDNG** [comment]
> 你试试用鼠标右键点块，会有一个对话框用于编辑。

okok可以了，右键可以编辑。但我还是建议把红色字的部分做成鼠标点击的按钮，感觉会更符合（我的）操作直觉

**Comment by PYUDNG** [comment]
ok挺好的，测试制作了一下在百合会签到的脚本，打开页面、判断元素存在、判断元素文本内容、流程控制、捕获网页元素都没啥问题，可以实现功能而且不用写代码
想问问捕获元素用的是什么方法，自动生成xpath或者css选择器吗？如何应对网页结构变化呢？

**Comment by NXY666** [comment]
> ok挺好的，测试制作了一下在百合会签到的脚本，打开页面、判断元素存在、判断元素文本内容、流程控制、捕获网页元素都没啥问题，可以实现功能而且不用写代码
> 想问问捕获元素用的是什么方法，自动生成xpath或者css选择器吗？如何应对网页结构变化呢？

获取css选择器我用的这个库：https://github.com/fczbkk/css-selector-generator

如果是捕获的元素，它没有冗余设计，变了应该就炸了。

不过宏录制有冗余设计，有两套css选择器，一个和树结构无关（用id、class、tag），一个和dom树结构相关。

嘿嘿，因为是毕设，有的设计没时间写就阉了😁

**Comment by NXY666** [comment]
> okok可以了，右键可以编辑。但我还是建议把红色字的部分做成鼠标点击的按钮，感觉会更符合（我的）操作直觉

是个好的想法。

**Comment by PYUDNG** [comment]
居然是毕设//会持续维护吗，感觉低代码脚本还挺好用的；如果把开发目标上面的功能都一个一个一个实现出来的话，应该还会有不小提升，说不定还能赚到金金金金金金钱钱钱钱钱钱…

哦对了，这个issue可以close掉了

**Comment by NXY666** [comment]
> 居然是毕设//会持续维护吗，感觉低代码脚本还挺好用的；如果把开发目标上面的功能都一个一个一个实现出来的话，应该还会有不小提升，说不定还能赚到金金金金金金钱钱钱钱钱钱…
> 
> 哦对了，这个issue可以close掉了

如果有时间当然会维护的。前一段时间在写另一个项目“swift-share”，写点原生html换换口味。

最近要面试力，人已经麻了 :(
